version: '3.8'

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: saleinnova
      MYSQL_ROOT_PASSWORD: 29062002
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '3307:3306'
    networks:
      springboot-mysql-net:

  lead-service:
    container_name: lead-service
    build:
      context: iLead
      dockerfile: iLead/Dockerfile
    ports:
      - '8082:8082'
    depends_on:
      - mysqldb
    networks:
        springboot-mysql-net:
    restart: on-failure

networks:
  springboot-mysql-net:



